import cv2 as cv
import numpy as np
img= cv.imread('cat.jpg')
def rescaleFrame(frame, scale=0.50):
    width = int(frame.shape[1]*scale)
    height = int(frame.shape[0]*scale)
    dimensions=(width,height)
    return cv.resize(frame,dimensions,interpolation=cv.INTER_AREA)
rescaled_image=rescaleFrame(img)    
cv.imshow('image', rescaled_image)
cv.imshow('Car',img)
blank = np.zeros(img.shape,dtype='uint8')
cv.imshow('blank',blank)
gray= cv.cvtColor(rescaled_image,cv.COLOR_BGR2GRAY)
cv.imshow('Gray',gray)
blur=cv.GaussianBlur(gray,(5,5),cv.BORDER_DEFAULT)
canny=cv.Canny(blur,125,175)
cv.imshow('Canny',canny)
#ret, thresh =cv.threshold(gray,125,255,cv.THRESH_BINARY)
#cv.imshow("thresh",thresh)
contours,hierarchies = cv.findContours(canny,cv.RETR_LIST,cv.CHAIN_APPROX_NONE)
print(f'{len(contours)} contour(s) found!')
cv.drawContours(blank,contours,-1,(0,0,255),1)
cv.imshow('Contours Drw',blank)
cv.waitKey(0)